### ISSUE TITLE
Extracting as plain text the  lm() formula shown in the plot.

### ISSUE THREAD

**Issue by sfd99** [EvaMaeRey/ggols#2]
**_Hi Gina,_**

Your **ggols** Penguins plot examples
and Flipbook 
are fantastic,
(I mean that 100% !).

**quick Q:**

How to
extract **as plain text**,
the  lm() formulas:
     ie: **y = 0.25x + ....** ,
shown inside the result plots.

Formulas are really
useful for  further "downstream" processing,
(avoid typing the formula by hand...).

_Thanks, Gina!._
SFd99
latest R, Rstudio and Ubuntu Linux 20.04.
San Francisco

**Comment by EvaMaeRey** [comment]
New to me https://datalorax.github.io/equatiomatic/ may be of interest to you as well, and better suited to this problem?
